<package format="3">

  <name>chess_perception</name>
  <version>0.2.0</version>
  <description>
    Perception node for new chess pipeline.
  </description>
  <author>Michael Ferguson</author>
  <maintainer email="mike@vanadiumlabs.com">Michael Ferguson</maintainer>
  <license>GPL</license>
  <url>http://ros.org/wiki/chess_perception</url>
  
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>chess_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>geometry_msgs</depend>
  <depend>image_transport</depend>
  <depend>libpcl-all-dev</depend>
  <depend>opencv2</depend>
  <depend>pcl_conversions</depend>
  <depend>pcl_ros</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
