# A pose, reference frame, timestamp, and type
Header header
geometry_msgs/Pose pose
int32 type

# chess piece definitions
int32 BLACK_KING=-7
int32 BLACK_QUEEN=-6
int32 BLACK_ROOK=-5
int32 BLACK_BISHOP=-4
int32 BLACK_KNIGHT=-3
int32 BLACK_PAWN=-2
int32 BLACK_UNKNOWN=-1
int32 UNKNOWN=0
int32 WHITE_UNKNOWN=1
int32 WHITE_PAWN=2
int32 WHITE_KNIGHT=3
int32 WHITE_BISHOP=4
int32 WHITE_ROOK=5
int32 WHITE_QUEEN=6
int32 WHITE_KING=7
